[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

#replace-with = "vendored-sources"

#[source."http://github.com/skydig/lan_switch"]
#git = "http://github.com/skydig/lan_switch"
#replace-with = "vendored-sources"


#[source.vendored-sources]
#directory = "vendor"

[target.armv7-unknown-linux-gnueabihf]
ar = "arm-linux-gnueabihf-ar"
linker = "arm-linux-gnueabihf-gcc.r"

[target.aarch64-unknown-linux-gnu]
ar =  "aarch64-linux-ar"
linker =  "aarch64-linux-gcc"


